name: CI/CD Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
        mysql:
            image: mysql:8.0
            env:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_DATABASE: secretlab_tech_exercise
            ports:
              - 3306:3306
            options: >
              --health-cmd="mysqladmin ping --silent"
              --health-interval=10s
              --health-timeout=5s
              --health-retries=3

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache Composer Dependencies
      uses: actions/cache@v2
      with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
              composer-

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql

    - name: Install Dependencies
      run: composer install --no-interaction

    # - name: Wait for MySQL to Be Ready
    #   run: |
    #       for i in {30..0}; do
    #           if mysqladmin ping -h127.0.0.1 --silent; then
    #               break
    #           fi
    #           echo 'Waiting for MySQL to be ready...'
    #           sleep 1
    #       done

    - name: Copy .env
      run: |
          echo "Copying .env.ci to .env..."
          cp .env.ci .env
          echo "Contents of .env:"
          cat .env

    - name: Reset APP_KEY
      run: sed -i '/^APP_KEY=/d' .env

    - name: Generate Application Key
      run: php artisan key:generate

    # - name: Run Migrations
    #   run: php artisan migrate --force

    - name: Run Tests
      run: php artisan test
      env:
        DB_DATABASE: secretlab_tech_exercise

