name: CI/CD Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    -   name: Checkout Code
        uses: actions/checkout@v2

    -   name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
            path: vendor
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json', '**/composer.lock') }}
            restore-keys: |
                ${{ runner.os }}-composer-

    -   name: Install PHP
        uses: shivammathur/setup-php@v3
        with:
            php-version: 8.2
            tools: composer

    -   name: Validate Composer Installation
        run: composer validate

    -   name: Install Dependencies
        run: composer install --no-interaction

    -   name: Generate Application Key
        run: php artisan key:generate

    -   name: Copy .env
        run: |
            cp .env.ci .env

    -   name: Run Tests
        run: php artisan test --verbose
