name: CI/CD Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
        mysql:
            image: mysql:8.0
            env:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
                MYSQL_DATABASE: secretlab_tech_exercise_testing
            ports:
                - 3306:3306

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache Composer Dependencies
      uses: actions/cache@v2
      with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
              composer-

    - name: Cache PHP Extensions
      uses: actions/cache@v2
      with:
        path: /tmp/pear
        key: php-extensions-${{ runner.os }}-${{ hashFiles('**/*.php') }}
        restore-keys: |
            php-extensions-${{ runner.os }}-

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql

    - name: Install Dependencies
      run: composer install --no-interaction

    - name: Copy .env
      run: |
          cp .env.testing .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Optimize Laravel
      run: |
        php artisan optimize
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Create and Migrate Test Database
      run: |
        echo "Creating and migrating the test database..."
        php artisan migrate --env=testing
        php artisan db:seed --env=testing

    - name: Run Tests
      run: php artisan test
      env:
        DB_DATABASE: secretlab_tech_exercise_testing

    - name: Deploy to Railway
      run: |
        git remote add railway https://git.railway.app/3remes89/secretlab-tech-exercise.git
        git push railway master
